platform :ios, '10.0'
use_frameworks!

target 'SwiftIOSDemo' do
pod 'Alamofire', '~> 4.6.0'
pod 'Moya', '~> 11.0.0'
pod 'ObjectMapper', '~> 3.1.0'
pod 'Kingfisher', '~> 4.6.1'
pod 'SnapKit', '~> 4.0.0'
pod 'R.swift'
pod 'SwiftyAttributes'
pod 'SwiftDate', '~> 4.5.0'
end

